### ISSUE TITLE
Start sign TX stuck at Initiating on Trezor

### ISSUE THREAD

**Issue by whoabuddy** [hirosystems/multisig-stx-btc#3]
When trying to process a multisig transaction today ran into a snag: I can generate the pre-stx transaction and decode it, but when clicking Start Sign TX I get a spinner that reads "Initiating..." in the Trezor Connet tab that never changes.

There is one error in the console logs:

```
caught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin 'unknown' in a call to 'postMessage'.
    at va (https://connect.trezor.io/9/js/iframe.56cc0d4f60c6451e9da5.js:66:355165)
    at Ea (https://connect.trezor.io/9/js/iframe.56cc0d4f60c6451e9da5.js:66:356146)
```

Confirmed on both Linux and Mac, both using Chrome, my version is `Version 112.0.5615.165 (Official Build) (64-bit)`.

This is a clean install with no additional extensions, ad blockers, etc.

Also tried downloading the latest version of multisig-stx-btc with the fancy Generate Delegate TX button but same issue.

Also verified that I can access Trezor Suite for Web from the same browser/config with no issues.

---

Digging around in the code and with additional logging I can see some specific console output related to my TX, e.g.

```
signing with trezor
redeemscript (and output below it)
tx (and output below it)
SCRIPT ADDR and ADDR match, and show expected value
```

I suspect there's an issue here, but have no idea why since this worked for us just fine a month ago.

https://github.com/hirosystems/multisig-stx-btc/blob/623337403c95e9c386937d014629dc78e34de275/src/transacter.js#L620-L629

Inspecting the `txB` object shows a blank object for `txB.__inputs`, although the length is still reported as 1. Snippet from my object below:

```
  "maximumFeeRate": 2500,
  "__inputs": [
    {}
  ],
  "__tx": {
    "version": 1,
    "locktime": 0,
    "ins": [
      {
        "hash": {
          "type": "Buffer",
```

The normal logging that follows on lines 624/625 shows:

```
input
> {}
```

I put some logging in front of lines 626 and 628, 628 prints first and 626 prints second, output below:

```
returning signPromise
signProcess then block
```

It's the opposite order of what I expected, but both do process and guessing the hang-up is something to do with the original error reported at the beginning?

Happy to provide any more info if helpful, and would like to get this resolved asap!

**Comment by diwakergupta** [comment]
Hi @whoabuddy - as you can imagine, many in our team are pretty tied up with other pressing issues. This repo isn't very actively maintained - just want to set the expectations.

Meanwhile, are you able to reproduce this in other browsers like Firefox?

@janniks , could you take a look? I'm not sure how easy it is to reproduce this, maybe hopping on a call with Jason to live debug?

cc/ @saralab @smcclellan for visibility

**Comment by muneeb-ali** [comment]
I left a suggestion for him RE Trezor safety checks to "prompt" and latest version of Trezor. That helped me earlier for a similar (but not the same) issue.

**Comment by whoabuddy** [comment]
> as you can imagine, many in our team are pretty tied up with other pressing issues. This repo isn't very actively maintained - just want to set the expectations.

Thanks @diwakergupta for picking this up so quickly, I mainly wanted to report the issue to see if others are running into the same or if I missed something small in the procedure. We don't use this tool often but when we do it's for important things :wink: 

@muneeb-ali thank you for that missing piece, however I'm sad to report it didn't work. I'm still seeing the same console error, script outputs, and spinning "Initiating..." screen on the Trezor signing tab.

Before testing again I tried:

1. updating firmware from 2.5.3 -> 2.6.0
2. updating "Safety checks" setting, procedure below:
    - Access [Trezor Suite for Web](https://suite.trezor.io/web/)
    - Go to Settings > Device > Security > Safety checks and click Edit
    - Change from Strict to Prompt
    - Hold button on Trezor to confirm
    - *Note that this needs to be done each time the Trezor is connected.*

I also tried from Firefox, which provides a different console error:

```
Uncaught (in promise) DOMException: An invalid or illegal string was specified
```

I also noted with Firefox that I get stuck in the same state even if the Trezor is not unlocked, so it must be something passed when the popup is first created?

Looking at [blockstack-trezor-signer](https://github.com/stacks-network/blockstack-trezor-signer) one easy thing to try might be upgrading `@trezor/connect-web` from 9.0.0 to 9.0.8? (shot in the dark, couldn't find release notes now that v9 is in the main repo).

**Comment by janniks** [comment]
I’ll look into it, not sure how fast we can run a full test with Trezor. ~But there was a potentially related issue about Trezor requiring a dependency update soon.~ EDIT: I think that's all already covered

**Comment by whoabuddy** [comment]
> I’ll look into it, not sure how fast we can run a full test with Trezor. But there was a potentially related issue about Trezor requiring a dependency update soon.

Thanks! If there's anything I can do to help let me know, happy to jump on a call or try out some changes.

There were a few issues related to postMessage in the Trezor repo but nothing directly related from what I saw.

**Comment by whoabuddy** [comment]
Shout out to @janniks - he identified that the problem only exists when opening the index.html file directly.

Using `npx serve dist` and accessing the site at localhost worked as expected.

There's also a hosted version that worked as well: https://multisig-stx-btc.vercel.app/

Thank you :pray:
